In [ ]:
# numpy --> numpy stands for 'numerical python' powerful python library that is widely 
# used for scientific computing ,data , analysis ,and numerical computing task 

# numpy , an array is the foundamental object .. 

# array is used to store homogeneous data elements contiguous block of memory .. 

In [2]:
import numpy as np

In [10]:
l = [1,2,3,4,5]
arr = np.array(l)
print(arr)
print(arr.size)
print(arr.shape)
print(arr.ndim)
print(arr.dtype)
print(type(arr))

[1 2 3 4 5]
5
(5,)
1
int64
<class 'numpy.ndarray'>


In [14]:
arr = np.array([[10,20,30],[40,30,57]])

print(arr)
print(arr.size)
print(arr.shape)
print(arr.ndim)
print(arr.dtype)
print(type(arr))

[[10 20 30]
 [40 30 57]]
6
(2, 3)
2
int64
<class 'numpy.ndarray'>


In [27]:
# 3d array
arr = np.array(
    [
        [
            [1,2,3],
            [4,5,6]
        ],
        [
            [4,5,6],
            [5,7,8]
        ]
    ]
)

print(arr)
print(arr.shape)
print(arr.ndim)


[[[1 2 3]
  [4 5 6]]

 [[4 5 6]
  [5 7 8]]]
(2, 2, 3)
3


In [19]:
arr = np.arange(7)
print(arr)

[0 1 2 3 4 5 6]


In [24]:
arr = np.arange(1,9,1)
print(arr)

arr1 = arr.reshape(2,4)
print(arr1)


[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]


In [26]:
arr = np.arange(1,28,1).reshape(3,3,3)
print(arr)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [28]:
%timeit [j**1000 for j in range(1,9)]

20.9 μs ± 168 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [29]:
%timeit np.arange(1,9)**1000

3.56 μs ± 32.1 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [31]:
arr = np.array([1,2,3],ndmin = 10)
print(arr)

[[[[[[[[[[1 2 3]]]]]]]]]]


In [33]:
# arange() function -- always return 1d array
arr = np.arange(1,9)
print(arr)

[1 2 3 4 5 6 7 8]


In [36]:
arr = np.arange(1,19).reshape(3,3,2)
print(arr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]


In [38]:
# element fetch 1d array.. 
arr = np.array([1,2,3,4,5])
print(arr[0])
print(arr[-1])

1
5


In [45]:
arr = np.arange(1,13).reshape(4,3)
print(arr)
print(arr[3][2])
print()
print(arr[2])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
12

[7 8 9]


In [49]:
arr = np.arange(1,28).reshape(3,3,3)
print(arr)
print(arr.ndim)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
3


In [51]:
# direct iteration.
arr = np.array([10,20,30,40,50])
for i in arr:
    print(i,end = " ")

10 20 30 40 50 

In [76]:
# indirect iteration.. 
arr = np.array([10,20,30,40,50])
for i in range(len(arr)):
    print(arr[i],end = " ")

10 20 30 40 50 

In [78]:
arr = np.arange(1,13).reshape(3,4)
for i in arr:
    for j in i:
        print(j,end = " ")

1 2 3 4 5 6 7 8 9 10 11 12 

In [80]:
arr = np.arange(1,28).reshape(3,3,3)
for i in arr:
    for j in i:
        for k in j:
            print(k,end = " ")

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 

In [82]:
arr = np.arange(1,28).reshape(3,3,3)
for i in np.nditer(arr):
    print(i,end = " ")

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 

In [87]:
arr = np.arange(1,28).reshape(3,3,3)
for i,j in np.ndenumerate(arr):
    print(i,j)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(0, 2, 0) 7
(0, 2, 1) 8
(0, 2, 2) 9
(1, 0, 0) 10
(1, 0, 1) 11
(1, 0, 2) 12
(1, 1, 0) 13
(1, 1, 1) 14
(1, 1, 2) 15
(1, 2, 0) 16
(1, 2, 1) 17
(1, 2, 2) 18
(2, 0, 0) 19
(2, 0, 1) 20
(2, 0, 2) 21
(2, 1, 0) 22
(2, 1, 1) 23
(2, 1, 2) 24
(2, 2, 0) 25
(2, 2, 1) 26
(2, 2, 2) 27


In [2]:
import numpy as np

In [4]:
data = np.array([1, 2, 3])

data[1]
data[0:2]
data[1:]
data[-2:]

array([2, 3])

In [5]:
# How to create a basic array.. 
# This section covers np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace()

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [26]:
np.empty(3)

array([7.66800595e+00, 7.66800595e+00, 1.38812617e-07])